
print( "Welcome to Tonys Basic external Hexagonal Milling G-Code Creator")
print("This program will create G-code for milling a hexagonal profile. Please follow the prompts to input the necessary parameters.")      

ToolNo = input("What tool number are you using? ") 
ToolDia = input("What is the tool diameter? ") 
ToolDia = float(ToolDia)
ToolRad = (ToolDia/2)
ToolRad = float(ToolRad)

WrkOfset = input("What is the work offset? ") 
SpdleRpm = input("What is the spindle RPM? ") 

XPos = input("What is the X position of the hex centre? ") 
XPos = float(XPos)

YPos = input("What is the Y position of the hex centre? ") 
YPos = float(YPos)

ZRapid = input("What is the rapid Z position? ") 
ZRapid = float(ZRapid)
ZStart = input("What is the starting Z position? ") 
ZStart = float(ZStart)

ZCut = input("What is the Z cut increment? ")
ZCut = float(ZCut)
Nosteps = input("How many steps? ") 
Nosteps = int(Nosteps) 

Diam = input("What is the dimesion across the flats? ") 
Diam = float(Diam)
Rad = (Diam/2)
Rad = float(Rad)
DiamT = (Diam + ToolDia)
DiamT = float(DiamT)
RadT = (DiamT/2)
RadT = float(RadT)
PointDT = (DiamT/0.86602540378)
PointDT = float(PointDT)
PointDTH = (PointDT/2)
PointDTH = float(PointDTH)
PointDTQ = (PointDT/4)
PointDTQ = float(PointDTQ) 

Leadin = input("What is the lead-in distance? ")
Leadin = float(Leadin)

Feedrate = input("What is the feedrate? ") 
Feedrate = float(Feedrate)

PXDTH = (XPos + PointDTH)
PXDTH = float(PXDTH)
PXDTHr = ("%.2f" % (PXDTH))
PXDTHr = float(PXDTHr) 

NXDTH = (XPos - PointDTH)
NXDTH = float(NXDTH)
NXDTHr = ("%.2f" % (NXDTH))
NXDTHr = float(NXDTHr)

PXDTQ = (XPos + PointDTQ)
PXDTQ = float(PXDTQ)
PXDTQr = ("%.2f" % (PXDTQ))
PXDTHr = float(PXDTHr)

NXDTQ = (XPos - PointDTQ)
NXDTQ = float(NXDTQ)
NXDTQr = ("%.2f" % (NXDTQ))
NXDTHr = float(NXDTHr)

PYRT = (YPos + RadT)
PYRT = float(PYRT)
PYRTr = ("%.2f" % (PYRT))
PYRTr = float(PYRTr)

NYRT = (YPos - RadT)
NYRT = float(NYRT)
NYRTr = ("%.2f" % (NYRT))
NYRTr = float(NYRTr)


print("Generating G-code...") 
print("M97 P8000") 
print("M05") 
print("T" + ToolNo + " M06")  
print("M03 P" + SpdleRpm) 
print("G" + WrkOfset) 
print("G40") 
print("G98 G17") 
print("G00 X" + str(PointDTH + Leadin) + " Y" + str(YPos + Leadin))
print("G" + WrkOfset + " G00 Z" + str(ZRapid) + " G43 " + ToolNo + " M08") 
print("G01 Z" + str(ZStart) + " F" + str(Feedrate/2))
print("M97 P501 L" + str(Nosteps)) 
print("G00 Z" + str(ZRapid + 20) + " M09")
print("M05")
print("M97 P8000")
print("M30")

print("N501")
print("G91 G01 Z-" + str(ZCut) + " F" + str(Feedrate/2))
print("G90")
print("G03 X" + str(PXDTHr) + " Y" + str(YPos) + " J-" + str(Leadin) + " F" + str(Feedrate))
print("G01 X" + str(PXDTQr) + " Y" + str(NYRTr))
print("G01 X" + str(NXDTQr) + " Y" + str(NYRTr))
print("G01 X" + str(NXDTHr) + " Y" + str(YPos))
print("G01 X" + str(NXDTQr) + " Y" + str(PYRTr))
print("G01 X" + str(PXDTQr) + " Y" + str(PYRTr))
print("G01 X" + str(PXDTHr) + " Y" + str(YPos))
print("G03 X" + str(PXDTHr + Leadin) + " Y" + str(YPos - Leadin) + " I" + str(Leadin))
print("G01 X" + str(PXDTHr + Leadin) + " Y" + str(YPos + Leadin))
print("M99")


print("N8000") 
print("G00 G90 G99 G97 M09") 
print("G53 G00 G40 Z0") 
print("G53 G00 G40 X0 Y0") 
print("M01") 
print("M99") 